# Generated by Django 4.0.4 on 2022-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmit',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formsubmit',
            name='photo',
            field=models.TextField(max_length=10),
        ),
    ]
