# Generated by Django 4.0.4 on 2022-05-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_alter_formsubmit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmit',
            name='photo',
            field=models.ImageField(upload_to='useruploads'),
        ),
    ]
