# Generated by Django 4.0.4 on 2022-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0009_alter_formsubmit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmit',
            name='photo',
            field=models.FileField(upload_to='useruploads'),
        ),
    ]
