# Generated by Django 4.0.4 on 2022-05-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0012_alter_formsubmit_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmit',
            name='url',
        ),
        migrations.AlterField(
            model_name='formsubmit',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
