# Generated by Django 4.0.4 on 2022-05-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0014_alter_formsubmit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmit',
            name='url',
            field=models.URLField(default='useriploads', max_length=100),
        ),
    ]
