# Generated by Django 4.0.4 on 2022-05-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0015_formsubmit_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmit',
            name='photo',
        ),
    ]
