# Generated by Django 4.0.4 on 2022-05-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0016_remove_formsubmit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmit',
            name='photo',
            field=models.FileField(default=0, upload_to='useruploads'),
        ),
        migrations.AlterField(
            model_name='formsubmit',
            name='url',
            field=models.URLField(default='useruploads', max_length=100),
        ),
    ]
