# Generated by Django 4.0.4 on 2022-05-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0017_formsubmit_photo_alter_formsubmit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmit',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
