# Generated by Django 4.0.4 on 2022-05-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0020_formsubmit_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmit',
            name='url',
        ),
    ]
