# Generated by Django 4.0.4 on 2022-05-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0021_remove_formsubmit_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='userjourneydata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.FileField(upload_to='')),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('journeyname', models.TextField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
