# Generated by Django 4.0.4 on 2022-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0022_userdata_userjourneydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjourneydata',
            name='location',
        ),
        migrations.AddField(
            model_name='userjourneydata',
            name='journeylocation',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='userjourneydata',
            name='placelocation',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
