# Generated by Django 4.0.4 on 2022-05-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0024_userjourneydata_key_alter_userjourneydata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjourneydata',
            name='journeylocation',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='userjourneydata',
            name='journeyname',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userjourneydata',
            name='placelocation',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
