# Generated by Django 4.0.4 on 2022-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0025_alter_userjourneydata_journeylocation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
        migrations.RemoveField(
            model_name='userjourneydata',
            name='key',
        ),
        migrations.AddField(
            model_name='userjourneydata',
            name='name',
            field=models.TextField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='userjourneydata',
            name='personimage',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
