# Generated by Django 4.0.4 on 2022-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0026_delete_userdata_remove_userjourneydata_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjourneydata',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
