# Generated by Django 4.0.4 on 2022-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0027_userjourneydata_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjourneydata',
            name='keyid',
            field=models.IntegerField(default=0),
        ),
    ]
